language: go
go:
  - 1.13.x
  - 1.14.x
before_install:
  - go get -u golang.org/x/lint/golint
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
script:
  - test -z "`gofmt -l .`"
  - test -z "`golint ./...`"
  - $GOPATH/bin/goveralls -service=travis-ci
  - cd example && ./linux64_build.sh
